
#####
##### DO NOT EDIT THIS FILE
#####

define say
	$(info [Assignment 3] $1)
endef


#
CC := g++
COMMONFLAGS := -Wall -pedantic -std=c++17 -g
COMPILEFLAGS := $(COMMONFLAGS) -c
LINKFLAGS := $(COMMONFLAGS) -pthread


#
BIN_NAME := main
BIN := ./$(BIN_NAME)
#
BIN_TESTS_NAME := main-tests
BIN_TESTS := ./$(BIN_TESTS_NAME)


#
default:	help


#
help:
	@echo "Assignment 3 - Makefile Menu"
	@echo
	@echo "make build         ==> Attempt to build main and main-tests"
	@echo
	@echo "make run           ==> Run the program contained in main.cpp (see note inside file)"
	@echo "make debug         ==> Debug the main.cpp program with gdb"
	@echo
	@echo "make tests         ==> Test your program"
	@echo "make debug-tests   ==> Debug the tester"
	@echo
	@echo "make clean         ==> Remove object files, the main executables, and other temporary files"


#
build:	$(BIN) $(BIN_TESTS)
.PHONY: build


#
run:	$(BIN)
	$(BIN)
.PHONY: run


#
debug:	$(BIN)
	gdb $(BIN) -ex run
.PHONY: debug


#
gradescope: test
tests:	test
test:	$(BIN_TESTS)
	$(BIN_TESTS)
.PHONY: gradescope tests test


#
debug-test:		debug-tests
debug-tests:	$(BIN_TESTS)
	gdb $(BIN_TESTS) -ex run
.PHONY: debug-test


#
$(BIN):	main.o functions.o
	$(CC) $(LINKFLAGS) $^ -o $@


#
$(BIN_TESTS):	CPP_Tests.o functions.o
	$(CC) $(LINKFLAGS) $^ -o $@


#
main.o:	main.cpp functions.hpp
	$(CC) $(COMPILEFLAGS) $< -o $@


#
functions.o:	functions.cpp functions.hpp
	$(CC) $(COMPILEFLAGS) $< -o $@


#
CPP_Tests.o:	CPP_Tests.cpp functions.hpp puhp-tests/*
	$(CC) $(COMPILEFLAGS) $< -o $@


#
clean:
	-rm *.o
	-rm $(BIN)
	-rm $(BIN_TESTS)
	-rm sync*.txt
	-rm results.json
.PHONY: clean





